spring:
  application:
    name: event-management
  datasource:
    url: jdbc:mysql://db:3306/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver